#lists
class_files = \
	bin/vialab/SMT/SMTProxyTuioListener.class \
	bin/vialab/SMT/AndroidToTUIO.class \
	bin/vialab/SMT/event/TouchEvent.class \
	bin/vialab/SMT/event/TouchListener.class \
	bin/vialab/SMT/Finger.class \
	bin/vialab/SMT/MainZone.class \
	bin/vialab/SMT/MouseToTUIO.class \
	bin/vialab/SMT/renderer/P3DDSRenderer.class \
	bin/vialab/SMT/renderer/PGLDSRenderer.class \
	bin/vialab/SMT/renderer/PGraphics3DDelegate.class \
	bin/vialab/SMT/renderer/PGraphicsOpenGLDelegate.class \
	bin/vialab/SMT/Simulation.class \
	bin/vialab/SMT/SMT.class \
	bin/vialab/SMT/SMTTouchManager.class \
	bin/vialab/SMT/SMTTuioListener.class \
	bin/vialab/SMT/SMTUtilities.class \
	bin/vialab/SMT/TexturedTouchDrawer.class \
	bin/vialab/SMT/Touch.class \
	bin/vialab/SMT/TouchClient.class \
	bin/vialab/SMT/TouchDraw.class \
	bin/vialab/SMT/TouchDrawer.class \
	bin/vialab/SMT/TouchPair.class \
	bin/vialab/SMT/TouchSource.class \
	bin/vialab/SMT/TouchState.class \
	bin/vialab/SMT/TuioConnectionException.class \
	bin/vialab/SMT/util/ZonePicker.class \
	bin/vialab/SMT/Zone.class \

source_files = \
	src/vialab/SMT/SMTProxyTuioListener.java \
	src/vialab/SMT/AndroidToTUIO.java \
	src/vialab/SMT/event/TouchEvent.java \
	src/vialab/SMT/event/TouchListener.java \
	src/vialab/SMT/Finger.java \
	src/vialab/SMT/MainZone.java \
	src/vialab/SMT/MouseToTUIO.java \
	src/vialab/SMT/renderer/P3DDSRenderer.java \
	src/vialab/SMT/renderer/PGLDSRenderer.java \
	src/vialab/SMT/renderer/PGraphics3DDelegate.java \
	src/vialab/SMT/renderer/PGraphicsOpenGLDelegate.java \
	src/vialab/SMT/Simulation.java \
	src/vialab/SMT/SMT.java \
	src/vialab/SMT/SMTTouchManager.java \
	src/vialab/SMT/SMTTuioListener.java \
	src/vialab/SMT/SMTUtilities.java \
	src/vialab/SMT/TexturedTouchDrawer.java \
	src/vialab/SMT/Touch.java \
	src/vialab/SMT/TouchClient.java \
	src/vialab/SMT/TouchDraw.java \
	src/vialab/SMT/TouchDrawer.java \
	src/vialab/SMT/TouchPair.java \
	src/vialab/SMT/TouchSource.java \
	src/vialab/SMT/TouchState.java \
	src/vialab/SMT/TuioConnectionException.java \
	src/vialab/SMT/util/ZonePicker.java \
	src/vialab/SMT/Zone.java \

source_zone = \
	src/vialab/SMT/zone/ButtonZone.java \
	src/vialab/SMT/zone/CheckBoxZone.java \
	src/vialab/SMT/zone/ContainerZone.java \
	src/vialab/SMT/zone/ImageZone.java \
	src/vialab/SMT/zone/KeyboardZone.java \
	src/vialab/SMT/zone/LeftPopUpMenuZone.java \
	src/vialab/SMT/zone/PatternUnlockZone.java \
	src/vialab/SMT/zone/PieMenuZone.java \
	src/vialab/SMT/zone/ShapeZone.java \
	src/vialab/SMT/zone/SlideRevealZone.java \
	src/vialab/SMT/zone/SliderZone.java \
	src/vialab/SMT/zone/SwipeKeyboard.java \
	src/vialab/SMT/zone/TabZone.java \
	src/vialab/SMT/zone/TextureZone.java \
	src/vialab/SMT/zone/TextZone.java \

source_keyboard = \
	src/vialab/SMT/swipekeyboard/AnchorZone.java \
	src/vialab/SMT/swipekeyboard/ArrowKeysLayout.java \
	src/vialab/SMT/swipekeyboard/CondensedLayout.java \
	src/vialab/SMT/swipekeyboard/DebugSwipeKeyboardListener.java \
	src/vialab/SMT/swipekeyboard/DefaultSwipeResolver.java \
	src/vialab/SMT/swipekeyboard/ExtendedLayout.java \
	src/vialab/SMT/swipekeyboard/KeyZone.java \
	src/vialab/SMT/swipekeyboard/ModifierKeyZone.java \
	src/vialab/SMT/swipekeyboard/SwipeKeyboardEvent.java \
	src/vialab/SMT/swipekeyboard/SwipeKeyboardLayout.java \
	src/vialab/SMT/swipekeyboard/SwipeKeyboardListener.java \
	src/vialab/SMT/swipekeyboard/SwipeKeyEvent.java \
	src/vialab/SMT/swipekeyboard/SwipeKeyListener.java \
	src/vialab/SMT/swipekeyboard/SwipeKeyZone.java \
	src/vialab/SMT/swipekeyboard/SwipeResolver.java \